---
- name: Configurar ambiente Cypress
  hosts: all
  become: yes

  tasks:
    - name: Instalar Node.js
      apt:
        name: nodejs
        state: present
      become: yes

    - name: Instalar gerenciador de pacotes NPM
      apt:
        name: npm
        state: present
      become: yes

    - name: Instalar Cypress
      npm:
        name: cypress
        global: yes
        state: present
      become: yes

